# Generated by Django 4.2.20 on 2025-03-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Depoimentos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("depoimento", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Equipe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome_adv", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Especialidades",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("especialidade", models.CharField(max_length=100)),
                ("descricao_especialidade", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Sobre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quemsomos", models.TextField()),
            ],
        ),
    ]
