# Generated by Django 4.2.20 on 2025-03-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="perfil_adv",
            field=models.TextField(default="Escreva seu perfil"),
        ),
        migrations.AlterField(
            model_name="depoimentos",
            name="depoimento",
            field=models.TextField(default="Escreva seu depoimento"),
        ),
        migrations.AlterField(
            model_name="especialidades",
            name="descricao_especialidade",
            field=models.TextField(default="Escreva sobre a especialidade"),
        ),
    ]
