# Generated by Django 4.2.20 on 2025-03-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_equipe_perfil_adv_alter_depoimentos_depoimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="depoimentos",
            name="cliente_depoimento",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="depoimentos",
            name="depoimento",
            field=models.TextField(default="Escreva seu depoimento", null=True),
        ),
        migrations.AlterField(
            model_name="especialidades",
            name="descricao_especialidade",
            field=models.TextField(default="Escreva sobre a especialidade", null=True),
        ),
        migrations.AlterField(
            model_name="especialidades",
            name="especialidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sobre",
            name="quemsomos",
            field=models.TextField(default="Escreva sobre a empresa", null=True),
        ),
    ]
