# Generated by Django 4.2.20 on 2025-03-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_depoimentos_cliente_depoimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="website/"),
        ),
    ]
