# Generated by Django 5.1.7 on 2025-03-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_equipe_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidades',
            old_name='especialidade',
            new_name='nome_especialidade',
        ),
    ]
