# Generated by Django 5.1.7 on 2025-05-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_especialidade_especialidades_nome_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidades',
            name='descricao_especialidade',
            field=models.TextField(default='Escreva sobre a especialidade.', null=True),
        ),
    ]
