# Generated by Django 5.1.7 on 2025-05-03 04:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_especialidades_descricao_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidades',
            name='descricao_especialidade',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
