# Generated by Django 5.1.7 on 2025-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_especialidades_descricao_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidades',
            name='resumo_especialidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
