# Generated by Django 5.1.7 on 2025-05-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_especialidades_resumo_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidades',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='media/icones/'),
        ),
    ]
