# Generated by Django 5.1.7 on 2025-05-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_especialidades_icone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depoimentos',
            options={'verbose_name': 'Depoimento', 'verbose_name_plural': 'Depoimentos'},
        ),
        migrations.AlterModelOptions(
            name='equipe',
            options={'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipe'},
        ),
        migrations.AlterModelOptions(
            name='especialidades',
            options={'verbose_name': 'Especialidade', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='sobre',
            options={'verbose_name': 'Quem Somos', 'verbose_name_plural': 'Quem Somos'},
        ),
        migrations.AddField(
            model_name='especialidades',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
