# Generated by Django 5.1.7 on 2025-05-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_depoimentos_options_alter_equipe_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidades',
            name='slug',
        ),
    ]
