# Generated by Django 5.1.7 on 2025-05-06 18:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_especialidades_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidades',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='nome_especialidade', unique=True),
        ),
    ]
