# Generated by Django 5.1.7 on 2025-05-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_blog',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog'),
        ),
    ]
