# Generated by Django 5.1.7 on 2025-05-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_post_photo_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_blog',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
